name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.9

      - name: Generate coverage report
        run: |
          cd app
          make report
        env:
          CC_TEST_REPORTER_ID: 7e4b9cbb41c9a07292f6068f373a71732121f7690893f4d106b4f287dfa6f7ef
          JACOCO_SOURCE_PATH:  app/src/main/java
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: ${{ github.workspace }}/app/build/build/reports/test/test/jacocoTestReport.xml:jacoco
          coverageInputType: jacoco