name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.9

      - name: Generate coverage report
        run: |
          cd app
          make report
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          JACOCO_SOURCE_PATH: app/src/main/java

      - name: Format coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageInputType: jacoco
          coverageFile: ${{ github.workspace }}/app/build/build/reports/test/test/jacocoTestReport.xml
          JACOCO_SOURCE_PATH: app/src/main/java

      - name: Upload coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageInputType: jacoco
          coverageFile: ${{ github.workspace }}/app/build/build/reports/test/test/jacocoTestReport.xml